version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfiles/api.Dockerfile
    image: neo-api
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always


  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s


  worker:
    build:
      context: .
      dockerfile: Dockerfiles/worker.Dockerfile
    image: neo-worker
    container_name: worker
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - broker


  broker:
    image: rabbitmq:3-alpine
    container_name: broker
    ports:
      - 5672:5672
    env_file:
      - .env
      